theme: jekyll-theme-minimal
logo: https://i2.wp.com/opderhueh.de/wp-content/uploads/2016/02/logo-wp-titel_trans.gif?fit=418%2C418
title: hier der Titel
description: hier könnte die neue Beschreibung stehen
